import { SidebarInset, SidebarProvider } from "@ui/components/sidebar";
import type { Metadata } from "next";
import Header from "@/components";
import { AppSidebar } from "@/components/app-sidebar";
import { MenuConfig } from "@/constants/menuConfig";

export const metadata: Metadata = {
	title: "Admin",
	description: "Generated by admin",
};

export default function AuthLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<SidebarProvider>
			<AppSidebar routes={MenuConfig} />
			<SidebarInset className="contain-inline-size">
				<Header />
				<main className="px-4 lg:px-8 py-4 flex-1 flex flex-col mx-auto w-full">
					{children}
				</main>
			</SidebarInset>
		</SidebarProvider>
	);
}
