import { SidebarProvider } from "@ui/components/sidebar";
import type { Metadata } from "next";
import { AppSidebar } from "@/components/app-sidebar";
import { MenuConfig } from "@/constants/menuConfig";

export const metadata: Metadata = {
	title: "Admin",
	description: "Generated by admin",
};

export default function AuthLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<div className="flex min-h-svh w-full">
			<SidebarProvider>
				<AppSidebar routes={MenuConfig} />
				<main className="px-4 lg:px-8 py-4 flex-1 flex flex-col mx-auto w-full">
					{children}
				</main>
			</SidebarProvider>
		</div>
	);
}
