import type { Route } from "@ui/types/nav";
import type { Metadata } from "next";
import { AppSidebarStatic } from "@/components/app-sidebar-static";

export const metadata: Metadata = {
	title: "Admin",
	description: "Generated by admin",
};

const demoRoutes: Route[] = [
	{
		group: "Main",
		children: [
			{
				title: "Dashboard",
				url: "/",
				permissions: [],
			},
			{
				title: "Products",
				url: "/products",
				permissions: [],
				children: [
					{
						title: "All Products",
						url: "/products/all",
						permissions: [],
					},
					{
						title: "Categories",
						url: "/products/categories",
						permissions: [],
					},
				],
			},
		],
	},
	{
		group: "Settings",
		children: [
			{
				title: "Profile",
				url: "/settings/profile",
				permissions: [],
			},
			{
				title: "Team",
				url: "/settings/team",
				permissions: [],
			},
		],
	},
];

export default function AuthLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<div className="flex min-h-svh w-full">
			<AppSidebarStatic routes={demoRoutes} />
			<main className="px-4 lg:px-8 py-4 flex-1 flex flex-col mx-auto w-full">
				{children}
			</main>
		</div>
	);
}
